In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("Salary Data.csv")
df.head()

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0

In [18]:
df = df.drop_duplicates()

(325, 6)

In [21]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.shape

(325, 6)

In [23]:
df.isnull().sum()

Age                    1
Gender                 1
Education Level        1
Job Title              1
Years of Experience    1
Salary                 1
dtype: int64

In [24]:
df[df.isnull().any(axis=1)]

     Age Gender Education Level Job Title  Years of Experience  Salary
172  NaN    NaN             NaN       NaN                  NaN     NaN

In [25]:
df = df.dropna()

In [26]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 324 entries, 0 to 371
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Age                  324 non-null    float64
 1   Gender               324 non-null    object
 2   Education Level      324 non-null    object
 3   Job Title            324 non-null    object
 4   Years of Experience  324 non-null    float64
 5   Salary               324 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.7+ KB

In [28]:
df.describe()

              Age  Years of Experience         Salary
count  324.000000           324.000000     324.000000
mean    37.382716            10.058642   99985.648148
std      7.185844             6.650470   48652.271440
min     23.000000             0.000000     350.000000
25%     31.000000             4.000000   55000.000000
50%     36.500000             9.000000   95000.000000
75%     44.000000            16.000000  140000.000000
max     53.000000            25.000000  250000.000000

In [30]:
df["Gender"].value_counts()

Gender
Male      170
Female    154
Name: count, dtype: int64

In [31]:
df["Education Level"].value_counts()

Education Level
Bachelor's    191
Master's       91
PhD            42
Name: count, dtype: int64

In [32]:
df["Job Title"].nunique()

174